### PR TITLE
update e2e versions

### PR DESCRIPTION
**Pull request by ystkfujii**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1975
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1972
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1970
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1969
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1965
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1964
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1959
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1955
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1953
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1951
- closes https://github.com/vmware-tanzu/sonobuoy/issues/1947

**Special notes for your reviewer**:

**Release note**:
```
updated e2e command to include most recent Kubernetes versions
```

### CODE REVIEW

**Comment by ystkfujii** [comment]
I ran gather_e2e_data.sh and committed.
However, I did not check the contents of the file.

**Comment by ystkfujii** [comment]
@franknstyle Could you please review it ?

**Comment by mohitsharma-in** [comment]
Can you please rebase this branch

**Comment by ystkfujii** [comment]
> Can you please rebase this branch

rebased !

**Pull request merged**
