### PR TITLE
WIP Emits CloudEvents with status changes

### PR DESCRIPTION
**Pull request by johnSchnake**
Any status change would trigger an event; this includes
changes in plugin status meaning that as E2E tests finish
then sonobuoy would emit a cloudEvent.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**
- Fixes #

**Special notes for your reviewer**:

**Release note**:
```
release-note
```

### CODE REVIEW

**Comment by johnSchnake** [comment]
Would like just a simple cloudevents echo-er as a sidecar with sonobuoy to test this. Thought that would already exist but may need to just build/push one?

**Comment by wilsonehusin** [comment]
@n3wscott CloudEvents :tada: `:n3wscott:`

**Comment by johnSchnake** [comment]
If this is all it takes then 👍 We just need a DD about what events to send, their types, etc. I think we'd need to have good docs  on a feature like this from the start or its unusable mostly.

So I think open questions would be:
 - List of events names/types
 - structure of those values (status change here was straight forward since its json that was already exposed)
 - when to send events
 - presumably, we'd need a flag to specify where to send events
 - need to allow multiple addresses for recipients? Or will we only send them to one?
 - Do we need to allow users to specify which events to get or do we just send them all and let the receiver filter?

Anything else?

**Comment by wilsonehusin** [comment]
so... I think most points above can be iterated upon, but if we can shift the JSON statuses to CloudEvents-compliant format, then the rest can take shape as we figure out "how are we going to serve this" while getting some input from folks upstream (like the iicoop who uses Sonobuoy quite extensively iirc).

**Comment by wilsonehusin** [comment]
alternatively, what an MVP could be is to have `sonobuoy status --progress` which shows how many tests have run and time elapsed with regular progress bar.

we can achieve this without CloudEvents -- but I think if we start promoting progress bar as a feature, folks might want to get creative on event consumers which makes me think it might be beneficial for us to have the structure in first 😉

**Comment by johnSchnake** [comment]
@wilsonehusin The progress bar is very low hanging fruit; that info is all available from the data in `sonobuoy status --json`. If you want you can experiment with different output formats.

There are the various `--wait` options where it can wait silently or with periodic output. Perhaps you can just add another one that is optional for now (just to see how it works) that has `--wait=progress` and will output/update progress bars and/or failures for the various plugins.

**Comment by johnSchnake** [comment]
Could even make a separate issue for that. I think it is a nobrainer that we need to utilize that; we just hadn't gotten around to it yet

**Pull request closed without merging**
