### PR TITLE
pkg/client/logs.go: retry watching pods to stream logs from

### LINKED ISSUE #1064: 100% CPU usage after running "sonobuoy logs -f"
**What steps did you take and what happened:**
After running even single test, e.g.: 
```
sonobuoy run --e2e-focus 'Aggregator Should be able to support the 1.10 Sample API Server using the current Aggregator'
```

And then leaving `sonobuoy logs -f` running for (in my case 2h), the process starts consuming 100% CPU of a single core.

**What did you expect to happen:**
`sonobuoy` to not trigger fans in my laptop :)

**Anything else you would like to add:**
`strace` doesn't say much, didn't try `gdb` or anything:
```
$ sudo strace -p 2554549
strace: Process 2554549 attached
futex(0x555c4acd9468, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x555c4acd9468, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x555c4acd9468, FUTEX_WAIT_PRIVATE, 0, NULL
```

If you have some suggestions for debugging, please let me know.

**Environment:**

- Sonobuoy version: 
```
$ sonobuoy version --kubeconfig local-testing/kubeconfig 
Sonobuoy Version: v0.17.0
MinimumKubeVersion: 1.15.0
MaximumKubeVersion: 1.17.99
GitSHA: 
API Version:  v1.17.0
```
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: https://github.com/flexkube/libflexkube
- Cloud provider or hardware configuration: VirtualBox with Vagrant
- OS (e.g. from `/etc/os-release`): 
Kubernetes nodes:
```
core@controller01 ~ $ cat /etc/os-release 
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2345.99.1
VERSION_ID=2345.99.1
BUILD_ID=2019-12-19-0008
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2345.99.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```
Host (where `sonobuoy` runs):
```
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
- Sonobuoy tarball (which contains * below)

### PR DESCRIPTION
**Pull request by invidian**
**What this PR does / why we need it**:

TODO

**Which issue(s) this PR fixes**
- Fixes #1064

**Special notes for your reviewer**:

Draft PR, as I want this to go out for initial review, as I have little idea how to fix that "properly". Will improve the description etc tomorrow. Feel free to push additional fixes if needed.

**Release note**:
```
Prevent CPU drain when streaming logs from pods, when connection to API server breaks
```

### CODE REVIEW

**Comment by invidian** [comment]
Now I think, list of pods should be wiped on reconnect, otherwise logs will be showing twice.

**Comment by zubron** [comment]
Thanks for taking the time to submit this PR! I'm sorry it's taken me so long to get back to you.

I think this is along the right track. I came across something in client-go which seems to wrap up the approach used here: [`RetryWatcher`](https://github.com/kubernetes/client-go/blob/master/tools/watch/retrywatcher.go#L44-L57). This takes care of re-establishing the `Watch` in the case where it is closed. Out of curiosity I tried it out on a branch here: https://github.com/vmware-tanzu/sonobuoy/compare/master...zubron:watch-retry. In that branch I also set a timeout on the `ListOptions` to trigger the behaviour original behaviour. I think we'd still need some handling for the watcher being `Done` or the channel being closed, but in those cases, I think we would just return from the function. In my tests, the watcher gets re-established, and in cases where the client can no longer connect, an error message indicating that is printed.

The only thing is that I'm not sure what the `initialResourceVersion` should be when creating the RetryWatcher :confused: I think you can call `List` to get the `PodList` and use that list's `ResourceVersion` but I'm not sure.

Also, we still have the problem you mentioned where the logs would be duplicated upon reconnection. Do you think it would be enough to keep track of the pods we have seen and only send the pods which we haven't seen before on `podCh`?

**Comment by invidian** [comment]
I was aware of `RetryWatcher`, but I haven't figured out how to pass `ListOptions` to it, I didn't spent much time working on that, so nice work!

>The only thing is that I'm not sure what the initialResourceVersion should be when creating the RetryWatcher confused I think you can call List to get the PodList and use that list's ResourceVersion but I'm not sure.

As we explicitly ignore this parameter in closure, I think it doesn't matter what we pass, so long it passes this check: https://github.com/kubernetes/client-go/blob/master/tools/watch/retrywatcher.go#L67-L74.

It is then being passed here: https://github.com/kubernetes/client-go/blob/master/tools/watch/retrywatcher.go#L103-L105, but we ignore it in the branch you posted: https://github.com/vmware-tanzu/sonobuoy/compare/master...zubron:watch-retry#diff-7a369ae51c001d42bbaee0e2b0efd386R186.

>Also, we still have the problem you mentioned where the logs would be duplicated upon reconnection. Do you think it would be enough to keep track of the pods we have seen and only send the pods which we haven't seen before on podCh?

As far as I understand, if watching breaks, streaming logs may also break (e.g. network outage on client side). Then once watching is established, it would push no more pods, meaning that logs following will be broken (until new pods shows up etc).

Does streaming logs has its own retry logic? If I understand https://github.com/vmware-tanzu/sonobuoy/blob/master/pkg/client/logs.go#L353 correctly, it does not.

I see 2 paths here then:
- Store list of pods, which has already been sent to streaming and don't send duplicates. Perhaps `map[string]struct{}` with `pod.metadata.uid` as a key could be used here. This option assumes, that streaming request itself will re-establish the connection after network outage.
- When watching is re-established, cancel all currently opened streams, as next all pods will be added to streaming. We currently don't store the references to `logStreamer` objects, so we would have to add that + cancelling logic.

I am not very experienced in either go routines or working with `client-go`, but I'm happy to try resolving this and learn something new. But if this somehow becomes urgent, feel free to take over the PR :)

**Comment by invidian** [comment]
>Store list of pods, which has already been sent to streaming and don't send duplicates. Perhaps map[string]struct{} with pod.metadata.uid as a key could be used here. This option assumes, that streaming request itself will re-establish the connection after network outage.

After re-reading this, it seems that retry logic in streaming itself + keeping a map of logged pods seems like a good way to go. This way, when log following breaks for a given pod, logger may check if pod disappeared and if not, continue following it. And watching pod list will work independently. 

I wonder how logger should restart following the logs. Should we set some buffer there to read last N logs? If so, some log messages may be duplicated. Also reasonable N would depend on the individual pod log rate and how fast we can re-establish following logs. Or should we start from 0? But then some log messages might get lost. Or we could track last log line and start from there then, that shouldn't be too computational intensive I think.

Selection_276

**Comment by johnSchnake** [comment]
Thanks @zubron for the branch; used that as the base for https://github.com/vmware-tanzu/sonobuoy/pull/1222 . Closing this.

**Pull request closed without merging**
