### PR TITLE
[fixit] wrong results link

### LINKED ISSUE #1035: Results page in README is 404
The README.md has a link to a page describing the results.

It points to: https://sonobuoy.io/docs/results.md

Which is 404

### PR DESCRIPTION
**Pull request by sebgoa**
**What this PR does / why we need it**:

A page in the readme sends to a 404

**Which issue(s) this PR fixes**
- Fixes #1035

**Special notes for your reviewer**:

**Release note**:
```
release-note
```

### CODE REVIEW

**Comment by johnSchnake** [comment]
What this actually needs is to have the results page added to the shortlinks document.

https://github.com/vmware-tanzu/sonobuoy/blob/master/site/_data/shortlinks.yml

That is why things like `sonobuoy.io/docs/faq` redirects automatically to the last released version of that doc.

Want to swap out your change for that?

**Comment by johnSchnake** [comment]
Also, if you update your PR, please squash your commits and then amend it with `--signoff` to sign your commit to pass the DCO signoff checker.

**Comment by sebgoa** [comment]
feel free to fix it yourself and discard this PR, I won't be able to get to this until tomorrow at best.

thanks for checking it

**Comment by johnSchnake** [comment]
@sebgoa OK will do; thanks for bringing it to our attention!

**Pull request closed without merging**
