### PR TITLE
Update Build with `golang:1.18`

### PR DESCRIPTION
**Pull request by hswong3i**
**What this PR does / why we need it**:

Currently I could build sonobuoy as .deb/.rpm with golang 1.17.6 successfully:
  - https://github.com/alvistack/vmware-tanzu-sonobuoy/commit/13fdb15e472e67c098ef320044608244fe373002#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0
  - https://github.com/alvistack/vmware-tanzu-sonobuoy/commit/13fdb15e472e67c098ef320044608244fe373002#diff-59dad63b4a45eead5357fdc79dfa9b64d295dee739c5214d9a6d84ed0e0e1feb
  - https://build.opensuse.org/package/show/home:alvistack/vmware-tanzu-sonobuoy-0.56.4

BTW, in case upgrade with golang 1.18.1, the result build:
  - The build could complete successfully
  - `sonobuoy version` could run successfully
  - BUT running `sonobuoy run --mode=certified-conformance` showing runtime error.

So this PR try to trigger the CI build with golang:1.18 for debugging.

**Release note**:
```
Update Build with `golang:1.18`
```

### CODE REVIEW

**Comment by johnSchnake** [comment]
Panic during unit tests 
```
--- FAIL: TestUnmarshallWithExtraVolumes (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b614a]

goroutine 21 [running]:
testing.tRunner.func1.2({0xb0dfa0, 0x11231c0})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0xb0dfa0, 0x11231c0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/modern-go/reflect2.(*frozenConfig).Type2(0xb2fae0, {0xce3ee0, 0xafc8c0})
	/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/reflect2.go:157 +0x4a
...
...
```

from kuberuntime:
```
if err := kuberuntime.DecodeInto(Decoder, manifest, &parsed); err != nil {
  t.Fatalf("couldn't decode manifest: %v", err)
}
```

**Comment by johnSchnake** [comment]
I'm all about bumping those versions as we can; so take a look into the source of that panic if you can or if we need to bump any other versions for compatibility and we can move forward.

**Comment by hswong3i** [comment]
So we should update to https://github.com/modern-go/reflect2/releases/tag/v1.0.2 which "fix go 1.18 compatibility"

**Comment by hswong3i** [comment]
So ‘golang.org/x/crypto’ also need to update due to CVE

**Comment by hswong3i** [comment]
Seems `go.sum` need to be cleanup (by running multiple times) with:
```
go mod tidy
rm -rf vendor
go mod download
go mod vendor
```

**Review by johnSchnake — APPROVED** [review]

**Comment by hswong3i** [comment]
@johnSchnake thank you very much ;-)

**Pull request merged**
